import Link from "next/link";
import Image from "next/image";
import bosy from "../../../../public/images/bosy.jpg";

async function getProducts() {
  const res = await fetch("https://fakestoreapi.com/products");

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}
export const metadata = {
  title: "MyShop - Products",
  description: "Generated by create next app",
  icons: { icon: ["/favicon.ico?v=4"] },
};

export default async function Product() {
  const data = await getProducts();

  return (
    <div className="p-14 flex flex-wrap gap-8 ">
      {data.map((product) => (
        <Link
          key={product.id}
          href={`/product/${product.id}`}
          className="hover:bg-gray-300 rounded-xl"
        >
          <div className="border border-cyan-300 rounded-lg shadow-lg flex flex-col justify-center items-center w-80 h-96">
            <div className="w-60 h-60 relative ">
              <Image
                src={product.image}
                alt={product.title}
                layout="fill"
                objectFit="cover"
                className="rounded-lg"
              />
            </div>
            <div className="">
              <h1 className="text-lg font-medium mt-2 text-center line-clamp-2 text-cyan-600 ">
                {product.title}
              </h1>
              <p className="text-neutral-500 text-left  font-light line-clamp-3 p-2 max-w-xs">
                {product.description}
              </p>
            </div>
          </div>
        </Link>
      ))}
    </div>
  );
}
