import Image from "next/image";
import shop from "../../public/images/shop.svg";
import Link from "next/link";
export const metadata = {
  title: "MyShop - Home",
  description: "Generated by create next app",
  icons: { icon: ["/favicon.ico?v=4"] },
};

export default function Home() {
  return (
    <div className="flex justify-between my-32 mx-60 space-x-36">
      <div>
        <h1 className=" home_h1 text-5xl font-bold uppercase text-left max-w-sm">
          welcome to your best online shop destination
        </h1>
        <p className=" text-neutral-500 mt-4 text-xl text-justify max-w-sm">
          Discover a world of endless shopping possibilities at our online
          store. Browse, choose and order your favorite products from the
          comfort of your home.
        </p>
        <Link href={"/product"}>
          <button className="mt-4 py-2 px-4 bg-cyan-600 text-white rounded hover:bg-cyan-700">
            Shop Now
          </button>
        </Link>
      </div>
      <div>
        <Image src={shop} alt="Profile Image" className="w-2/3 rounded" />
      </div>
    </div>
  );
}
